"use client";
//import type { Metadata } from "next";
import localFont from "next/font/local";
import { useState } from 'react';
import "./globals.css";
import { usePathname } from 'next/navigation';
import { MapPinCheck, Menu, X } from 'lucide-react'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [menuOpen, setMenuOpen] = useState(false);

  const toggleMenu = () => {
    setMenuOpen(!menuOpen);
  };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="navbar w-full h-[60px] fixed top-0 z-10 text-white flex items-center justify-between px-8 bg-opacity-50 shadow-lg">
          <div className="icon">
            <h2 className="logo text-orange-400 text-[30px] font-bold flex items-center">UniPATH <MapPinCheck className=""/></h2>
          </div>
          <div className="menu h-full hidden md:flex">
            <ul className="flex items-center justify-center space-x-8 text-center">
              <li className="">
                <a href="/" className={`font-semibold ${pathname === '/' ? 'underline text-orange-400' : ''}`}>
                  HOME
                </a>
              </li>
              <li className="">
                <a href="/about" className={`font-semibold ${pathname === '/about' ? 'underline text-orange-400' : ''}`}>
                  ABOUT
                </a>
              </li>
              <li className="">
                <a href="/map" className={`font-semibold ${pathname === '/map' ? 'underline text-orange-400' : ''}`}>
                  MAP
                </a>
              </li>
            </ul>
          </div>

          <div className="md:hidden">
            <button onClick={toggleMenu} className="text-white">
              {menuOpen ? <X size={24} /> : <Menu size={24} />}
            </button>
          </div>
        </div>

        {menuOpen && (
          <div className="md:hidden bg-gray-800 fixed top-[60px] w-full z-10 text-white">
            <ul className="flex flex-col items-center space-y-4 py-4 pb-8">
              <li>
                <a href="/" className={`font-semibold ${pathname === '/' ? 'underline text-orange-400' : ''}`}>HOME</a>
              </li>
              <li>
                <a href="/about" className={`font-semibold ${pathname === '/about' ? 'underline text-orange-400' : ''}`}>ABOUT</a>
              </li>
              <li>
                <a href="/map" className={`font-semibold ${pathname === '/map' ? 'underline text-orange-400' : ''}`}>MAP</a>
              </li>
            </ul>
          </div>
        )}

        {children}
      </body>
    </html>
  );
}
